name: Build Flatpak Repository

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:46
      options: --privileged
    permissions:
      contents: write

    strategy:
      max-parallel: 1
      matrix:
        manifest:
          - build-aux/org.project_spiel.SpielInstaller.json
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: project-spiel/flatpaks
          ssh-key: ${{ secrets.FLATPAKS_KEY }}
          ref: main
          path: flatpaks

      - name: Setup repo directory
        run: |
          mkdir -p flatpaks/repo
          ln -s flatpaks/repo repo
  
      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build
        id: build
        uses: andyholmes/flatter@main
        with:
          files: ${{ matrix.manifest }}
          arch: x86_64
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          cache-key: ''

      - name: Deploy
        run: |
          cd flatpaks
          git config --global user.email "me@project-spiel.org"
          git config --global user.name "Spiel Robot"
          git add repo
          git commit -m "Updated Spiel-It packages"
          git pull --rebase
          git push -f origin main
          
  
